# Generated by Django 5.2.10 on 2026-04-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PAI', 'Painting'), ('DRA', 'Drawing')], default='PAI', max_length=3)),
                ('image', models.ImageField(upload_to='artworks/')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Unique id at the end of this artwork's url", unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('year_of_creation', models.DecimalField(decimal_places=0, max_digits=4)),
                ('width_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('depth_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('medium', models.CharField(choices=[('INK', 'Ink'), ('OIL', 'Oil'), ('ACRL', 'Acrylic'), ('PENC', 'Pencil'), ('OTH', 'Other')], default='OIL', max_length=4)),
                ('custom_medium', models.CharField(blank=True, default='', max_length=50)),
                ('material', models.CharField(choices=[('CAN', 'Canvas'), ('PAP', 'Paper'), ('OTH', 'Other')], default='CAN', max_length=3)),
                ('custom_material', models.CharField(blank=True, default='', max_length=50)),
                ('style', models.CharField(choices=[('ABS', 'Abstract'), ('SUR', 'Surrealism'), ('EXP', 'Expressionism'), ('OTH', 'Other')], default='ABS', max_length=4)),
                ('custom_style', models.CharField(blank=True, default='', max_length=50)),
                ('artwork_description', models.TextField()),
            ],
        ),
    ]
