# Generated by Django 5.2.10 on 2026-04-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/')),
                ('title', models.CharField(max_length=75)),
                ('blog_text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(help_text="Unique id at the end of the blog's url", unique=True)),
            ],
        ),
    ]
